# Generated by Django 2.0.2 on 2018-03-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikipediaPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('scanned', models.BooleanField(default=False)),
                ('scanned_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
